org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=chat_canvas
mod_name=Chat Canvas
mod_license=MIT
mod_version=1.0.0
mod_group_id=io.github.ikunkk02
mod_authors=\u5BFF\u4E91
mod_description=A visual and highly customizable client-side chat HUD editor for Minecraft.

org.gradle.java.home=C:/Program Files/Java/jdk-17.0.3.1
