package io.github.ikunkk02.chatcanvas.voice;

public enum VoiceInputState {
	DISABLED,
	UNSUPPORTED_PLATFORM,
	MODEL_MISSING,
	MODEL_DOWNLOADING,
	MODEL_VERIFYING,
	MODEL_EXTRACTING,
	MODEL_INSTALLING,
	MODEL_LOADING,
	IDLE,
	OPENING_CHAT,
	WAITING_FOR_SPEECH,
	SPEAKING,
	WAITING_FOR_ENDPOINT,
	FINALIZING,
	COMMITTING_RESULT,
	COMPLETED,
	CANCELLED,
	ERROR
}
